### ISSUE TITLE
Add an apk to test on mobile phones

### ISSUE THREAD

**Issue by datteroandrea** [choutkamartin/next-auth-capacitor#1]
If possible try to add the downloadable APK so I can install it on my phone to try the authentication flow on mobile.

**Comment by choutkamartin** [comment]
Hi, I will do that in the upcoming days

**Comment by choutkamartin** [comment]
I have added a downloadable APK under 0.1.0 release. It should be fully working and the app itself doesn't require any other permissions than just a network one.
